#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irseekLeft,     sensorI2CCustom)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     irseekRight,    sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorSpokes,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    Wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    DropRight,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    DropLeft,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	{ // Left motor check
		motor[motorLeft] = 75;
		wait1Msec(2000);

		motor[motorLeft] = 0;
		wait1Msec(250);
	}

	PlaySound(soundBeepBeep);

	while (true) {  // Right motor check
		if (nNxtButtonPressed == 1)
		{
			motor[motorRight]=75;
			wait1Msec(2000);

			motor[motorRight]=0;
			wait1Msec(250);

			break;
		}
	}

	PlaySound(soundBeepBeep);

	while (true) {
		if (nNxtButtonPressed == 1)
		{
			motor[motorLeft]=75;
			wait1Msec(2000);

			motor[motorLeft]=0;
			wait1Msec(250);

			break;
		}
	}

	int currentCount = 0;

	while (true) { // encoder check
		{
			if (nNxtButtonPressed == 1)
			{
				nMotorEncoder[motorRight] = 0;

				while(abs(nMotorEncoder[motorRight]) <= 2* 1440) {

					motor[motorRight] = 50;

					currentCount = nMotorEncoder[motorRight];
				}

			}
		}
	}

	motor[motorRight] = 0;

	PlaySound(soundBeepBeep);

	while (true) { // take lift up
		if (nNxtButtonPressed == 1)
		{
			motor[motorLift]=75;
			wait1Msec(1000);

			motor[motorLift]=0;
			wait1Msec(250);

			break;
		}
	}

	PlaySound(soundBeepBeep);

	while (true) { // bring lift down
		if (nNxtButtonPressed == 1)
		{
			motor[motorLift] = -75;
			wait1Msec(1000);

			motor[motorLift] = 0;
			wait1Msec(250);

			break;
		}
	}

	PlaySound(soundBeepBeep);

	while (true) { // move spokes motor
		if (nNxtButtonPressed == 1)
		{
			motor[motorSpokes] = 75;
			wait1Msec(1000);

			motor[motorSpokes] = 0;
			wait1Msec(250);

			motor[motorSpokes] = -75;
			wait1Msec(1000);

			motor[motorSpokes] = 0;
			wait1Msec(250);

			break;
		}
	}

	PlaySound(soundBeepBeep);

	// Check all servos

	short currentWristPos = ServoValue[Wrist];
	short currentDropLeftPos = ServoValue[DropLeft];
	short currentDropRightPos = ServoValue[DropRight];

	while (true) { // check wrist
		if (nNxtButtonPressed == 1)
		{
			servoTarget[Wrist] =  currentWristPos + 25;
			wait1Msec(1000);

			servoTarget[Wrist] =  currentWristPos;
			wait1Msec(1000);

			break;
		}
	}

	PlaySound(soundBeepBeep);

	while (true) { // check left hook
		if (nNxtButtonPressed == 1)
		{
			servoTarget[DropLeft] =  currentDropLeftPos + 25;
			wait1Msec(1000);

			servoTarget[DropLeft] =  currentDropLeftPos;
			wait1Msec(1000);

			break;
		}
	}

	PlaySound(soundBeepBeep);

	while (true) { // check right hook
		if (nNxtButtonPressed == 1)
		{
			servoTarget[DropRight] =  currentDropRightPos + 25;
			wait1Msec(1000);

			servoTarget[DropRight] =  currentDropRightPos;
			wait1Msec(1000);

			break;
		}
	}

	PlaySound(soundBeepBeep);

	//	exit();
}//end main
